applications/employer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "employer_app"

urlpatterns = [
    path('ListarTodosLosEmpleados',
         views.ListarTodosLosEmpleados.as_view(),
         name='ListarTodosLosEmpleados'
         ),
    path('AdministrarTodosLosEmpleados',
         views.AdministrarTodosLosEmpleados.as_view(),
         name='AdministrarTodosLosEmpleados'
         ),
    path('ActualizarEmpleado/<pk>/',
         views.ActualizarEmpleado.as_view(), name='ActualizarEmpleado'),
    path('EliminarEmpleado/<pk>/',
         views.EliminarEmpleado.as_view(), name='EliminarEmpleado'),
    path('CrearEmpleado',
         views.CrearEmpleado.as_view(), name='CrearEmpleado'),
    path('ListAllEmployerByDepartment', views.ListAllEmployerByArea.as_view()),
    path('ListarEmpleadosPorArea/<shortNameDepartment>',
         views.ListarEmpleadosPorArea.as_view(), name='ListarEmpleadosPorArea'),
    path('ListAllEmployerByAreaChar', views.ListAllEmployerByAreaChar.as_view()),
    path('ListAllEmployerByAreaChar2',
         views.ListAllEmployerByAreaChar2.as_view()),
    path('ListSkillsByEmploy', views.ListSkillsByEmploy.as_view()),
    path('EmployerDetailView/<pk>/', views.EmployerDetailView.as_view()),
    path('DetallesDelEmpleado/<pk>/',
         views.DetallesDelEmpleado.as_view(),
         name='DetallesDelEmpleado'),
    path('EmployerCreateView', views.EmployerCreateView.as_view()),
    path('EmployerCreateView2', views.EmployerCreateView2.as_view()),
    path('SuccesView', views.SuccesView.as_view(), name='SuccesView'),
    path('EmployerUpdate/<pk>/',
         views.EmployerUpdate.as_view(), name='EmployerUpdate'),
    path('EmployerDelete/<pk>/',
         views.EmployerDelete.as_view(), name='EmployerDelete'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.employer.urls')),
    re_path('', include('applications.department.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/employer/models.py
from django.db import models
from applications.department.models import Department
from ckeditor.fields import RichTextField
# Create your models here.
JOB_CHOICES = (
    ('0', 'Ingeniero'),
    ('1', 'Arquitecto'),
    ('2', 'Desarrollador'),
    ('3', 'Programador'),
)


class Skills(models.Model):
    skill = models.CharField('skill', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return self.skill + ' - ' + str(self.id)


class Employer(models.Model):
    name = models.CharField('name', max_length=50)
    lastname = models.CharField('lastName', max_length=50)
    job = models.CharField('job', max_length=1, choices=JOB_CHOICES)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    cv = RichTextField(default='None', blank=True)
    avatar = models.ImageField(upload_to='empleados', blank=True, null=True)
    fullname = models.CharField(
        'fullName', max_length=200, blank=True, null=True)
    skills = models.ManyToManyField(Skills)
    # image = models.ImageField('image', upload_to=None, height_field=None, width_field=None, max_length=None)

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

    def __str__(self):
        return self.lastname + ' - ' + self.job + ' - ' + self.name

applications/employer/forms.py
from django import forms

from .models import Employer


class EmpleadoForm(forms.ModelForm):
    """Form definition for Empleado."""

    class Meta:
        """Meta definition for Empleadoform."""

        model = Employer
        fields = ('name', 'lastname', 'job',
                  'department', 'cv', 'avatar', 'fullname', 'skills',)
        widgets = {
            'skills': forms.CheckboxSelectMultiple()
        }

applications/employer/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
# Como se quieren los empleados se debe importar el modelo
from .models import Employer
from .forms import EmpleadoForm
# Create your views here.

# Listar todos los empleados


# class ListarTodosLosEmpleados(ListView):
#     model = Employer
#     template_name = 'employer/Listar_Todos_Los_Empleados.html'
#     context_object_name = 'lista_empleados'

class ListarTodosLosEmpleados(ListView):
    template_name = 'employer/Listar_Todos_Los_Empleados.html'
    paginate_by = 2
    ordering = 'lastname'
    context_object_name = 'lista_empleados'
    model = Employer

    def get_queryset(self):
        palabraClave = self.request.GET.get('kword', '')
        listaEmpleados = Employer.objects.filter(
            lastname__icontains=palabraClave
        )
        print('listaEmpleados:', listaEmpleados)
        return listaEmpleados


class ListarEmpleadosPorArea(ListView):
    template_name = 'employer/ListarEmpleadosPorArea.html'
    context_object_name = 'lista_empleados_por_area'
    model = Employer
    # queryset = Employer.objects.filter(
    #     department__shortNameDepartment='C'
    # )

    def get_queryset(self):
        area = self.kwargs.get('shortNameDepartment')
        lista = Employer.objects.filter(

            department__shortNameDepartment=area
        )
        return lista


class AdministrarTodosLosEmpleados(ListView):
    template_name = 'employer/AdministrarTodosLosEmpleados.html'
    paginate_by = 2
    ordering = 'lastname'
    context_object_name = 'lista_empleados'
    model = Employer

    def get_queryset(self):
        palabraClave = self.request.GET.get('kword', '')
        listaEmpleados = Employer.objects.filter(
            lastname__icontains=palabraClave
        )
        print('listaEmpleados:', listaEmpleados)
        return listaEmpleados


class ActualizarEmpleado(UpdateView):
    template_name = "employer/ActualizarEmpleado.html"
    context_object_name = 'ActualizarEmpleado'
    model = Employer
    fields = [
        'name',
        'lastname',
        'job',
        'department',
        'skills',
    ]
    success_url = reverse_lazy('employer_app:AdministrarTodosLosEmpleados')


class EliminarEmpleado(DeleteView):
    model = Employer
    template_name = "employer/EliminarEmpleado.html"
    success_url = reverse_lazy('employer_app:AdministrarTodosLosEmpleados')


class CrearEmpleado(CreateView):
    model = Employer
    template_name = "employer/CrearEmpleado.html"
    # fields = ['name', 'lastname', 'job', 'department', 'cv','skills']
    # fields = ('__all__')
    form_class = EmpleadoForm
    # success_url = './SuccesView'
    success_url = reverse_lazy('employer_app:AdministrarTodosLosEmpleados')

    def form_valid(self, form):
        employer = form.save(commit=False)
        print(employer)
        employer.full_name = employer.name+' '+employer.lastname
        employer.save()
        return super(CrearEmpleado, self).form_valid(form)


class DetallesDelEmpleado(DetailView):
    model = Employer
    template_name = 'employer/DetallesDelEmpleado.html'
    context_object_name = 'employerDetailView'

    def get_context_data(self, **kwargs):
        context = super(DetallesDelEmpleado, self).get_context_data(**kwargs)
        context['skills'] = self.object.skills.all()
        context['titulo'] = 'Empleado del mes'
        return context

# Forma 1 Listar todos los empleados de un área de la empresa


class ListAllEmployerByArea(ListView):
    queryset = Employer.objects.filter(
        department__nameDepartment='Contabilidad'
    )
    template_name = 'employer/list_all_area.html'
    context_object_name = 'lista_empleados_area'
# Forma 2 Listar todos los empleados de un área de la empresa


# Listar todos los empleados por una palabra clave


class ListAllEmployerByAreaChar(ListView):
    def get_queryset(self):
        print('*********************')
        keyWord = self.request.GET.get('kword', '')
        print('keyWord:', keyWord)
        list = Employer.objects.filter(
            name=keyWord
        )
        print('list:', list)
        return list
    template_name = 'employer/list_all_areaChar.html'
    context_object_name = 'lista_empleados_areaChar'

# Listar todos los empleados por una palabra clave Paginación


class ListAllEmployerByAreaChar2(ListView):
    def get_queryset(self):
        keyWord = self.request.GET.get('kword2', '')
        print('keyWord:', keyWord)
        list = Employer.objects.filter(
            name=keyWord
        )
        print('list:', list)
        return list
    template_name = 'employer/list_all_areaChar2.html'
    paginate_by = 2
    context_object_name = 'lista_empleados_areaChar2'

# Listar habilidades de un empleado


class ListSkillsByEmploy(ListView):
    template_name = 'employer/listSkillsByEmploy.html'
    context_object_name = 'listSkillsByEmploy'

    def get_queryset(self):
        employ = Employer.objects.get(id=4)
        print(employ.skills.all())
        return employ.skills.all()

# Para usar la vista se debe activar la url


class EmployerDetailView(DetailView):
    model = Employer
    template_name = 'employer/employer_detail.html'
    context_object_name = 'employerDetailView'


class EmployerCreateView(CreateView):
    model = Employer
    template_name = "employer/employerCreateView.html"
    # fields = ['name', 'lastname', 'job', 'department', 'cv','skills']
    fields = ('__all__')
    success_url = './EmployerCreateView'


class SuccesView(TemplateView):
    template_name = "employer/successView.html"


class EmployerCreateView2(CreateView):
    model = Employer
    template_name = "employer/employerCreateView2.html"
    # fields = ['name', 'lastname', 'job', 'department', 'cv','skills']
    # fields = ('__all__')
    fields = ['name', 'lastname', 'job', 'department', 'cv', 'skills']
    # success_url = './SuccesView'
    success_url = reverse_lazy('employer_app:SuccesView')

    def form_valid(self, form):
        employer = form.save(commit=False)
        print(employer)
        employer.full_name = employer.name+' '+employer.lastname
        employer.save()
        return super(EmployerCreateView2, self).form_valid(form)


class EmployerUpdate(UpdateView):
    template_name = "employer/EmployerUpdate.html"
    model = Employer
    fields = [
        'name',
        'lastname',
        'job',
        'department',
        'skills',
    ]
    success_url = reverse_lazy('employer_app:SuccesView')


class EmployerDelete(DeleteView):
    model = Employer
    template_name = "employer/EmployerDelete.html"
    success_url = reverse_lazy('employer_app:SuccesView')

templates/employer/CrearEmpleado.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %} Crear Empleados {% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<h1>Registrar persona</h1>
<!--{{ form }}-->
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Guardar</button>
</form>
{% include 'conmon/footer.html'%}
<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/employer/DetallesDelEmpleado.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %}
<!-- # Objeto para el título
{{ employerDetailView.name }} {{ employerDetailView.lastname }}
<!-- # Objeto para el título -->
{% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<div class="ContainerDetalleEmpleado">
  <h1 class="ContainerDetalleEmpleadoName">
    {{ employerDetailView.name }} {{ employerDetailView.lastname }}
  </h1>
  <h3 class="ContainerDetalleEmpleadoTittle">Todos los datos</h3>
  <table class="ContainerDetalleEmpleadoTable">
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">Nombre:</td>
      <td class="ContainerDetalleEmpleadoTableListItem">
        {{ employerDetailView.name }}
      </td>
    </tr>
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">Apellido:</td>
      <td class="ContainerDetalleEmpleadoTableListItem">
        {{ employerDetailView.lastname }}
      </td>
    </tr>
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">Departamento:</td>
      <td class="ContainerDetalleEmpleadoTableListItem">
        {{ employerDetailView.department.nameDepartment }}
      </td>
    </tr>
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">
        Avatar: {% if employerDetailView.avatar %}
        <img
          src="{{ employerDetailView.avatar.url  }}"
          alt="Imagen del empleado"
        />{%else %}
        <img
          src="{% static 'images/usuario.jpg' %}"
          alt="Imagen del empleado"
        />
        {% endif %}
      </td>
    </tr>
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">Habilidades:</td>
      <td class="ContainerDetalleEmpleadoTableListItem">
        <ul>
          {% for habilidad in employerDetailView.skills.all %}
          <li>{{habilidad.skill}}</li>
          {% endfor %}
        </ul>
      </td>
    </tr>
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">Trabajo:</td>
      <td class="ContainerDetalleEmpleadoTableListItem">
        {{ employerDetailView.job }} {{ employerDetailView.get_job_display }}
      </td>
    </tr>
    <tr class="ContainerDetalleEmpleadoTableList">
      <td class="ContainerDetalleEmpleadoTableListItem">Título:</td>
      <td class="ContainerDetalleEmpleadoTableListItem">{{ titulo }}</td>
    </tr>
  </table>
</div>
<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/employer/EliminarEmpleado.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %} Eliminar Empleado {% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<div class="EliminarEmpleadoContainer">
  <h1>Eliminar Empleado: {{ object.name}} {{ object.lastname}}</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Confirmar</p>
    <button type="submit">Confirmar</button>
  </form>
</div>

<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/employer/EmployerDelete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Borrar</h1>
    <form method="POST">
      {% csrf_token %}
      <p>Confirmar</p>
      <button type="submit">Confirmar</button>
    </form>
  </body>
</html>

templates/employer/ListarEmpleadosPorArea.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %} Listar Empledos Por Departamentos {% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<div class="EmpledosPorDepartamentosContainer">
  <h1 class="EmpledosPorDepartamentosContainerTitle">Empleados</h1>
  <div class="EmpledosPorDepartamentosContainerSpace">
    <table class="ContainerListarTodosLosEmpleadosDatosTable">
      <thead class="ContainerListarTodosLosEmpleadosDatosTableHead">
        <tr class="ContainerListarTodosLosEmpleadosDatosTableHeadList">
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            ID
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Apellidos
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Nombres
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Departamento
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Acción
          </th>
        </tr>
      </thead>
      <tbody class="ContainerListarTodosLosEmpleadosDatosTableBody">
        {% for employ in lista_empleados_por_area %}
        <tr class="ContainerListarTodosLosEmpleadosDatosTableBodyList">
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.id }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.name }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.lastname }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.department }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            <a
              class="ContainerListarTodosLosEmpleadosDatosTableBodyListItemLink"
              href="{% url 'employer_app:DetallesDelEmpleado' employ.id  %}"
              >Ver</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/employer/Listar_Todos_Los_Empleados.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %} Listar Empleados {% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<div class="ContainerListarTodosLosEmpleados">
  <!-- Inicio Bloque contenedor título-->
  <div class="ContainerListarTodosLosEmpleadosTitulo">
    <h1>Lista de empleados</h1>
  </div>
  <!-- Fin Bloque contenedor título-->
  <!-- Inicio Bloque contenedor data-->
  <!-- Inicio Bloque formualrio data-->
  <form action="" method="GET">
    <div class="ContainerListarTodosLosEmpleadosBuscador">
      {% csrf_token %}
      <button
        type="submit"
        class="ContainerListarTodosLosEmpleadosBuscadorEspacio"
      >
        Buscar
      </button>
      <input
        class="ContainerListarTodosLosEmpleadosBuscadorEspacio"
        type="text"
        placeholder="Buscar Empleado"
        name="kword"
        id="kword"
      />
    </div>
  </form>
  <!-- Fin Bloque formualrio data-->
  <!-- Inicio Bloque Lista Empleados data-->
  <div class="ContainerListarTodosLosEmpleadosDatos">
    <table class="ContainerListarTodosLosEmpleadosDatosTable">
      <thead class="ContainerListarTodosLosEmpleadosDatosTableHead">
        <tr class="ContainerListarTodosLosEmpleadosDatosTableHeadList">
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            ID
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Apellidos
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Nombres
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Departamento
          </th>
          <th class="ContainerListarTodosLosEmpleadosDatosTableHeadListItem">
            Acción
          </th>
        </tr>
      </thead>
      <tbody class="ContainerListarTodosLosEmpleadosDatosTableBody">
        {% for employ in lista_empleados %}
        <tr class="ContainerListarTodosLosEmpleadosDatosTableBodyList">
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.id }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.name }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.lastname }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            {{ employ.department }}
          </td>
          <td class="ContainerListarTodosLosEmpleadosDatosTableBodyListItem">
            <a
              class="ContainerListarTodosLosEmpleadosDatosTableBodyListItemLink"
              href="{% url 'employer_app:DetallesDelEmpleado' employ.id  %}"
              >Ver</a
            >
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- Fin Bloque Lista Empleados data-->
  <!-- Inicio Bloque Paginador data-->
  <div>
    {% if is_paginated %}
    <ul class="pagination">
      <!-- Inicio Bloque Paginador data previous-->
      {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}"><<</a>
      </li>
      {% endif %}
      <!-- Fin Bloque Paginador data previous-->
      <!-- Inicio Bloque Paginador data páginas-->
      {% for pagina in paginator.page_range %}
      <!-- Inicio Bloque Paginador data páginas comparador-->
      {% if pagina == page_obj.number %}
      <li><a href="?page={{ pagina }}" class="active">{{ pagina }}</a></li>
      {% else %}
      <li><a href="?page={{ pagina }}">{{ pagina }}</a></li>
      {% endif %}
      <!-- Fin Bloque Paginador data páginas comparador-->
      {% endfor %}
      <!-- Fin Bloque Paginador data páginas-->
      <!-- Inicion Bloque Paginador data siguiente-->
      {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}">>></a>
      </li>
      <!-- Fin Bloque Paginador data siguiente-->
    </ul>
    {% endif %} {% endif %}
  </div>

  <!-- Fin Bloque Paginador data-->

  <!-- Fin Bloque contenedor data-->
</div>
<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/employer/employerCreateView.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Registrar persona</h1>
    <!--{{ form }}-->
    <form action="" method="POST">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Guardar</button>
    </form>
  </body>
</html>

templates/employer/employerCreateView2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Registrar persona</h1>
    <!--{{ form }}-->
    <form action="" method="POST">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Guardar</button>
    </form>
  </body>
</html>

templates/employer/employerUpdate.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Actualizar empleado</h1>
    <form method="POST">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">Actualizar</button>
    </form>
  </body>
</html>

templates/employer/employer_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Hola</h1>
    <p>Empleado: {{ employerDetailView }}</p>
    <h3>Todos los datos</h3>
    <p>{{ employerDetailView.name }}</p>
    <p>{{ employerDetailView.lastname }}</p>
    <p>{{ employerDetailView.skills }}</p>
    <p>{{ employerDetailView.job }}</p>
  </body>
</html>

templates/employer/list_all_area.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Lista por area</h1>
    {{ lista_empleados_area }}
    <ul>
      {% for empleado in lista_empleados_area %}
      <li>{{empleado.name}}</li>
      {% endfor %}
    </ul>
  </body>
</html>

templates/employer/list_all_areaChar.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Lista de empleados por Area</h1>
    <form method="GET" action>
      {% csrf_token %}
      <input
        type="text"
        id="kword"
        name="kword"
        placeholder="Escriba el nombre"
      />
      <button type="submit">Buscar</button>
      <h3>Lista resultados</h3>
      <ul>
        {% for empleado in lista_empleados_areaChar %}
        <li>{{empleado.name}} {{empleado.department}}</li>
        {% endfor %}
      </ul>
    </form>
  </body>
</html>

templates/employer/list_all_areaChar2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Lista de empleados por Area Paginados</h1>
    <form method="GET" action>
      {% csrf_token %}
      <input
        type="text"
        id="kword2"
        name="kword2"
        placeholder="Escriba el nombre"
      />
      <button type="submit">Buscar</button>
      <h3>Lista resultados</h3>
      <ul>
        {% for empleado in lista_empleados_areaChar2 %}
        <li>{{empleado.name}} {{empleado.lastname}} {{empleado.department}}</li>
        {% endfor %}
      </ul>
    </form>
  </body>
</html>

templates/employer/successView.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <h1>Listo :D</h1>
  </body>
</html>