applications/department/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "department_app"
urlpatterns = [
    path('NewDepartamentoView', views.NewDepartamentoView.as_view(),
         name='NewDepartamentoView'),
    path('ListarDepartamentos', views.ListarDepartamentos.as_view(),
         name='ListarDepartamentos'),
    path('CrearDepartamento', views.CrearDepartamento.as_view(),
         name='CrearDepartamento'),
]

applications/employer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "employer_app"

urlpatterns = [
    path('ListarTodosLosEmpleados',
         views.ListarTodosLosEmpleados.as_view(),
         name='ListarTodosLosEmpleados'
         ),
    path('AdministrarTodosLosEmpleados',
         views.AdministrarTodosLosEmpleados.as_view(),
         name='AdministrarTodosLosEmpleados'
         ),
    path('ActualizarEmpleado/<pk>/',
         views.ActualizarEmpleado.as_view(), name='ActualizarEmpleado'),
    path('EliminarEmpleado/<pk>/',
         views.EliminarEmpleado.as_view(), name='EliminarEmpleado'),
    path('CrearEmpleado',
         views.CrearEmpleado.as_view(), name='CrearEmpleado'),
    path('ListAllEmployerByDepartment', views.ListAllEmployerByArea.as_view()),
    path('ListarEmpleadosPorArea/<shortNameDepartment>',
         views.ListarEmpleadosPorArea.as_view(), name='ListarEmpleadosPorArea'),
    path('ListAllEmployerByAreaChar', views.ListAllEmployerByAreaChar.as_view()),
    path('ListAllEmployerByAreaChar2',
         views.ListAllEmployerByAreaChar2.as_view()),
    path('ListSkillsByEmploy', views.ListSkillsByEmploy.as_view()),
    path('EmployerDetailView/<pk>/', views.EmployerDetailView.as_view()),
    path('DetallesDelEmpleado/<pk>/',
         views.DetallesDelEmpleado.as_view(),
         name='DetallesDelEmpleado'),
    path('EmployerCreateView', views.EmployerCreateView.as_view()),
    path('EmployerCreateView2', views.EmployerCreateView2.as_view()),
    path('SuccesView', views.SuccesView.as_view(), name='SuccesView'),
    path('EmployerUpdate/<pk>/',
         views.EmployerUpdate.as_view(), name='EmployerUpdate'),
    path('EmployerDelete/<pk>/',
         views.EmployerDelete.as_view(), name='EmployerDelete'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.employer.urls')),
    re_path('', include('applications.department.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/conmon/divSpace.html
<div class="spaceDepartment">
  <h1>Departamento</h1>
  <form action="" method="post">
    {% csrf_token %}
    <h3 class="spaceDepartmentTittle">Datos empleado</h3>
    <div class="spaceDepartmentData">
      <div>Nombre empleado:</div>
      <div>{{ form.name }}</div>
      <div>Apellido empleado:</div>
      <div>{{ form.lastname }}</div>
    </div>
    <h3 class="spaceDepartmentTittle">Datos Departamento</h3>
    <div class="spaceDepartmentData">
      <div>Nombre departamento:</div>
      <div>{{ form.nameDepartment }}</div>
      <div>Sigla:</div>
      <div>{{ form.shortNameDepartment }}</div>
    </div>
    <div class="spaceDepartmentButton">
      <button type="submit">Guardar</button>
    </div>
  </form>
</div>

templates/conmon/footer.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %} {% load compress %} {% compress css %}
    <link
      type="text/x-scss"
      href="{% static 'department/footer.scss' %}"
      rel="stylesheet"
      media="screen"
    />
    {% endcompress %} {% include '../conmon/tittle.html' %}
  </head>
  <body>
    <div class="footer">Footer</div>
  </body>
</html>

templates/conmon/nav.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %} {% load compress %} {% compress css %}
    <link
      type="text/x-scss"
      href="{% static 'base/nav.scss' %}"
      rel="stylesheet"
      media="screen"
    />
    {% endcompress %} {% include '../conmon/tittle.html' %}
  </head>
  <body>
    <nav class="navigator">
      <ul class="navigatorLink">
        <li class="navigatorLinkItem">
          <img
            class="navigatorLinkItemImg"
            src="{% static 'images/Django.png' %}"
            alt=""
          />
        </li>
        <li class="navigatorLinkItem">
          <a href="{% url 'employer_app:ListarTodosLosEmpleados' %}">Listar</a>
        </li>
        <li class="navigatorLinkItem">
          <a href="{% url 'department_app:ListarDepartamentos' %}"
            >Departamentos</a
          >
        </li>
        <li class="navigatorLinkItem">
          <a href="{% url 'department_app:CrearDepartamento' %}"
            >Crear Departamento</a
          >
        </li>
        <li class="navigatorLinkItem">
          <a href="{% url 'employer_app:AdministrarTodosLosEmpleados' %}"
            >Administrar</a
          >
        </li>
      </ul>
      <ul class="navigatorLinkbtn">
        <li class="navigatorLinkItembtn">
          <a href="{% url 'employer_app:CrearEmpleado' %}">Crear empleado</a>
        </li>
      </ul>
    </nav>
  </body>
</html>

templates/conmon/tittle.html
<title>El título</title>