applications/department/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "department_app"
urlpatterns = [
    path('NewDepartamentoView', views.NewDepartamentoView.as_view(),
         name='NewDepartamentoView'),
    path('ListarDepartamentos', views.ListarDepartamentos.as_view(),
         name='ListarDepartamentos'),
    path('CrearDepartamento', views.CrearDepartamento.as_view(),
         name='CrearDepartamento'),
]

applications/employer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "employer_app"

urlpatterns = [
    path('ListarTodosLosEmpleados',
         views.ListarTodosLosEmpleados.as_view(),
         name='ListarTodosLosEmpleados'
         ),
    path('AdministrarTodosLosEmpleados',
         views.AdministrarTodosLosEmpleados.as_view(),
         name='AdministrarTodosLosEmpleados'
         ),
    path('ActualizarEmpleado/<pk>/',
         views.ActualizarEmpleado.as_view(), name='ActualizarEmpleado'),
    path('EliminarEmpleado/<pk>/',
         views.EliminarEmpleado.as_view(), name='EliminarEmpleado'),
    path('CrearEmpleado',
         views.CrearEmpleado.as_view(), name='CrearEmpleado'),
    path('ListAllEmployerByDepartment', views.ListAllEmployerByArea.as_view()),
    path('ListarEmpleadosPorArea/<shortNameDepartment>',
         views.ListarEmpleadosPorArea.as_view(), name='ListarEmpleadosPorArea'),
    path('ListAllEmployerByAreaChar', views.ListAllEmployerByAreaChar.as_view()),
    path('ListAllEmployerByAreaChar2',
         views.ListAllEmployerByAreaChar2.as_view()),
    path('ListSkillsByEmploy', views.ListSkillsByEmploy.as_view()),
    path('EmployerDetailView/<pk>/', views.EmployerDetailView.as_view()),
    path('DetallesDelEmpleado/<pk>/',
         views.DetallesDelEmpleado.as_view(),
         name='DetallesDelEmpleado'),
    path('EmployerCreateView', views.EmployerCreateView.as_view()),
    path('EmployerCreateView2', views.EmployerCreateView2.as_view()),
    path('SuccesView', views.SuccesView.as_view(), name='SuccesView'),
    path('EmployerUpdate/<pk>/',
         views.EmployerUpdate.as_view(), name='EmployerUpdate'),
    path('EmployerDelete/<pk>/',
         views.EmployerDelete.as_view(), name='EmployerDelete'),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.employer.urls')),
    re_path('', include('applications.department.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/department/models.py
from django.db import models

# Create your models here.


class Department(models.Model):
    nameDepartment = models.CharField('nameDepartment', max_length=50)
    shortNameDepartment = models.CharField(
        'shortNameDepartment', max_length=2, unique=True)
    activeDepartment = models.BooleanField('active', default=False)
    search_fields = ('nameDepartment', 'shortNameDepartment',)
    list_filter = ('nameDepartment',)

    class Meta:
        verbose_name = 'nameDepartment'
        verbose_name_plural = 'nameDepartments'
        ordering = ['nameDepartment']
        unique_together = ('nameDepartment', 'shortNameDepartment')

    def __str__(self):
        return self.nameDepartment + ' - ' + self.shortNameDepartment

applications/department/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    name = forms.CharField(max_length=50, required=False)
    lastname = forms.CharField(max_length=50, required=False)
    nameDepartment = forms.CharField(max_length=50, required=False)
    shortNameDepartment = forms.CharField(max_length=5, required=False)

applications/department/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormView
# Create your views here.
from .forms import NewDepartamentoForm
from applications.employer.models import Employer
from .models import Department


class ListarDepartamentos(ListView):
    model = Department
    template_name = "department/ListarDepartamentos.html"
    context_object_name = 'lista_empleados_departamento'


class CrearDepartamento(FormView):
    template_name = 'department/CrearDepartamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        departamento = Department(
            nameDepartment=form.cleaned_data['nameDepartment'],
            shortNameDepartment=form.cleaned_data['shortNameDepartment'],
        )
        departamento.save()
        nameF = form.cleaned_data['name']
        lastnameF = form.cleaned_data['lastname']
        Employer.objects.create(
            name=nameF,
            lastname=lastnameF,
            job='1',
            department=departamento
        )
        return super(CrearDepartamento, self).form_valid(form)


class IndexView(TemplateView):
    template_name = 'index.html'


class NewDepartamentoView(FormView):
    template_name = 'department/new_deparments.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        departamento = Department(
            nameDepartment=form.cleaned_data['nameDepartment'],
            shortNameDepartment=form.cleaned_data['shortNameDepartment'],
        )
        departamento.save()
        nameF = form.cleaned_data['name']
        lastnameF = form.cleaned_data['lastname']
        Employer.objects.create(
            name=nameF,
            lastname=lastnameF,
            job='1',
            department=departamento
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/department/CrearDepartamento.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %} Crear Departamento {% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<div class="space">
  <div class="spaceDepartment">
    <h1>Departamento</h1>
    <form action="" method="post">
      {% csrf_token %}
      <h3 class="spaceDepartmentTittle">Datos empleado</h3>
      <div class="spaceDepartmentData">
        <div>Nombre empleado:</div>
        <div>{{ form.name }}</div>
        <div>Apellido empleado:</div>
        <div>{{ form.lastname }}</div>
      </div>
      <h3 class="spaceDepartmentTittle">Datos Empleado</h3>
      <div class="spaceDepartmentData">
        <div>Nombre departamento:</div>
        <div>{{ form.nameDepartment }}</div>
        <div>Sigla:</div>
        <div>{{ form.shortNameDepartment }}</div>
      </div>
      <div class="spaceDepartmentButton">
        <button type="submit">Guardar</button>
      </div>
    </form>
  </div>
</div>
<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/department/Departamentos.html
<!-- Inicio Bloque contenedor-->
{% for departamento in lista_empleados_departamento %}
<option value="{{ departamento.shortNameDepartment }}">
  {{ departamento.nameDepartment }}
</option>
{% endfor %}

templates/department/ListarDepartamentos.html
{% extends 'base/base.html' %}
<!-- Se cargan los estáticos-->
{% load static %}
<!-- Se importa el título-->
{%block tittle %} Listar Departamentos {% endblock tittle %}
<!-- Se importa el body-->
{% block body %}
<!-- Se incluye el menú -->
{% include 'conmon/nav.html'%}
<!-- Inicio Bloque contenedor-->
<div class="DepartamentosContainer">
  <h1 class="DepartamentosContainerTitle">Listar Departamentos</h1>
  <div class="DepartamentosContainerSpace">
    {% for departamento in lista_empleados_departamento %}
    <div class="DepartamentosContainerItem">
      {{ departamento.nameDepartment }}
    </div>
    <div class="DepartamentosContainerItem">
      {{ departamento.shortNameDepartment }}
    </div>
    <div class="DepartamentosContainerItem">
      <a
        href="{% url 'employer_app:ListarEmpleadosPorArea' departamento.shortNameDepartment %}"
        >Ver empleados {{ departamento.shortNameDepartment }}</a
      >
    </div>
    {% endfor %}
  </div>
  <div class="DepartamentosContainerSpace"></div>
  <div class="DepartamentosContainerSpace"></div>
</div>
<!-- Fin Bloque contenedor-->
{% endblock body %}

templates/department/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>

templates/department/new_deparments.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %} {% load compress %} {% compress css %}
    <link
      type="text/x-scss"
      href="{% static 'department/main.scss' %}"
      rel="stylesheet"
      media="screen"
    />
    {% endcompress %} {% include '../conmon/tittle.html' %}
  </head>
  <body>
    {% include '../conmon/nav.html' %}
    <div class="space">
      <div class="spaceDepartment">
        <h1>Departamento</h1>
        <form action="" method="post">
          {% csrf_token %}
          <h3 class="spaceDepartmentTittle">Datos empleado</h3>
          <div class="spaceDepartmentData">
            <div>Nombre empleado:</div>
            <div>{{ form.name }}</div>
            <div>Apellido empleado:</div>
            <div>{{ form.lastname }}</div>
          </div>
          <h3 class="spaceDepartmentTittle">Datos Empleado</h3>
          <div class="spaceDepartmentData">
            <div>Nombre departamento:</div>
            <div>{{ form.nameDepartment }}</div>
            <div>Sigla:</div>
            <div>{{ form.shortNameDepartment }}</div>
          </div>
          <div class="spaceDepartmentButton">
            <button type="submit">Guardar</button>
          </div>
        </form>
      </div>
    </div>
    {% include '../conmon/footer.html' %}
  </body>
</html>